export interface Item {
  id: number;
  applicable_tax: 'DEFAULT' | 'EXEMPT' | 'PERCENT' | 'DEFAULT';
  availability_type: 'ON_STOCK' | 'BY_ORDER' | 'ALWAYS' | 'ALWAYS';
  background: string;
  brand_id: number | null;
  category_id: number | null;
  clave_sat: string | null;
  code: string | null;
  commanda_type_id: number | null;
  commission_currency_id: string;
  commission_type: 'NONE' | 'AMOUNT' | 'PERCENT' | 'NONE';
  commission: number;
  created_by_user_id: number | null;
  created: string | Date;
  currency_id: string;
  description: string | null;
  extra_name: string | null;
  form_id: number | null;
  response_requirement_qty: 'ONCE_PER_CLIENT' | 'ONCE_PER_SALE' | 'EVERY_ITEM' | 'ONCE_PER_SALE';
  for_reservation: 'YES' | 'NO' | 'NO';
  has_serial_number: 'NO' | 'YES' | 'NO';
  ieps_type: 'RATE' | 'AMOUNT' | 'RATE';
  ieps_value: number;
  image_id: number | null;
  image_style: 'COVER' | 'CONTAIN' | 'CONTAIN';
  json_tags: any | null;
  measurement_unit: string | null;
  name: string;
  note_required: 'NO' | 'YES' | 'NO';
  on_sale: 'NO' | 'YES';
  stock_type: 'NORMAL' | 'BATCH' | 'NORMAL';
  partial_sale: 'NO' | 'YES' | 'NO';
  period_type: 'BY_HOUR' | 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'MONTHLY';
  product_id: number | null;
  provider_user_id: number | null;
  reference_currency_id: string;
  reference_price: number;
  return_action: 'RETURN_TO_STOCK' | 'ADD_TO_MERMA' | 'TRANSFORM_INTO_ITEM' | 'RETURN_TO_STOCK';
  shadow_color: string;
  sort_weight: number;
  status: 'ACTIVE' | 'DELETED' | 'ACTIVE';
  tax_percent: number;
  text_color: string;
  text_style: 'NEVER' | 'CENTER' | 'DOWN' | 'CENTER';
  unidad_medida_sat_id: string;
  updated_by_user_id: number | null;
  updated: string | Date;
}


