export interface Item {
  id: number;
  applicable_tax: string | null;
  availability_type: string | null;
  background: string;
  brand_id: number | null;
  category_id: number | null;
  clave_sat: string | null;
  code: string | null;
  commanda_type_id: number | null;
  commission_currency_id: string;
  commission_type: string | null;
  commission: number;
  created_by_user_id: number | null;
  created: string | Date;
  currency_id: string;
  description: string | null;
  extra_name: string | null;
  form_id: number | null;
  response_requirement_qty: string | null;
  for_reservation: string | null;
  has_serial_number: string | null;
  ieps_type: string | null;
  ieps_value: number | null;
  image_id: number | null;
  image_style: string | null;
  json_tags: string | null;
  measurement_unit: string | null;
  name: string;
  note_required: string | null;
  on_sale: string | null;
  stock_type: string | null;
  partial_sale: string | null;
  period_type: string | null;
  product_id: number | null;
  provider_user_id: number | null;
  reference_currency_id: string;
  reference_price: number | null;
  return_action: string | null;
  shadow_color: string;
  sort_weight: number;
  status: string | null;
  tax_percent: number | null;
  text_color: string;
  text_style: string | null;
  unidad_medida_sat_id: string;
  updated_by_user_id: number | null;
  updated: string;
}


