export interface Order {
  id: number;
  address: string | null;
  amount_paid: number | null;
  ares: number;
  authorized_by: string | null;
  billing_address_id: number | null;
  billing_data_id: number | null;
  cancellation_reason: string | null;
  cancellation_timestamp: string | Date | null;
  cancelled_by_user_id: number | null;
  cashier_user_id: number | null;
  city: string | null;
  client_name: string | null;
  client_user_id: number | null;
  closed_by_user_id: number | null;
  closed_timestamp: string | Date | null;
  created: string | Date;
  currency_id: string;
  delivery_schedule: string | null;
  delivery_status: string | null;
  delivery_user_id: number | null;
  discount_calculated: number | null;
  discount: number | null;
  ecommerce_user_id: number | null;
  external_id: string | null;
  facturacion_code: string;
  facturado: string | null;
  facturacion_timestamp: string | Date | null;
  first_payment_date: string | null;
  frequency: string | null;
  guests: number;
  initial_payment: number | null;
  installment_amount: number | null;
  installment_months: number | null;
  installment_round_amount: number;
  installments: number | null;
  lat: number | null;
  lng: number | null;
  marked_for_billing: string | null;
  note: string | null;
  paid_status: string | null;
  paid_timetamp: string | Date | null;
  period_id: number | null;
  price_type_id: number;
  quote_id: number | null;
  sat_codigo_postal: string | null;
  sat_domicilio_fiscal_receptor: string;
  sat_exchange_rate: number | null;
  sat_factura_id: number | null;
  sat_forma_pago: string;
  sat_ieps: number | null;
  sat_isr: number | null;
  sat_pdf_attachment_id: number | null;
  sat_razon_social: string | null;
  sat_receptor_email: string | null;
  sat_receptor_rfc: string | null;
  sat_regimen_capital_receptor: string;
  sat_regimen_fiscal_receptor: string;
  sat_serie_consecutive: number | null;
  sat_serie: string | null;
  sat_uso_cfdi: string | null;
  sat_xml_attachment_id: number | null;
  service_type: string | null;
  shipping_address_id: number | null;
  shipping_cost: number | null;
  state: string | null;
  status: string | null;
  store_consecutive: number;
  store_id: number;
  subtotal: number | null;
  suburb: string | null;
  sync_id: string | null;
  system_activated: string | Date | null;
  table_id: number | null;
  tag: string | null;
  tax_percent: number | null;
  tax: number | null;
  total: number | null;
  updated: string;
  version_created: string;
  version_updated: string;
}


