export interface Order {
  id: number;
  address: string | null;
  amount_paid: number;
  ares: number;
  authorized_by: string | null;
  billing_address_id: number | null;
  billing_data_id: number | null;
  cancellation_reason: string | null;
  cancellation_timestamp: string | Date | null;
  cancelled_by_user_id: number | null;
  cashier_user_id: number | null;
  city: string | null;
  client_name: string | null;
  client_user_id: number | null;
  closed_by_user_id: number | null;
  closed_timestamp: string | Date | null;
  created: string | Date;
  currency_id: string;
  delivery_schedule: string | Date | null;
  delivery_status: 'PENDING' | 'SENT' | 'DELIVERED' | 'CANCELLED' | 'READY_TO_PICKUP' | 'PENDING';
  delivery_user_id: number | null;
  discount_calculated: number;
  discount: number;
  ecommerce_user_id: number | null;
  external_id: string | null;
  facturacion_code: string;
  facturado: 'NO' | 'YES' | 'NO';
  facturacion_timestamp: string | Date | null;
  first_payment_date: string | null;
  frequency: 'WEEKLY' | 'MONTHLY' | '2X_MONTHLY' | 'NONE' | 'NONE';
  guests: number;
  initial_payment: number;
  installment_amount: number | null;
  installment_months: number | null;
  installment_round_amount: any;
  installments: number | null;
  lat: number | null;
  lng: number | null;
  marked_for_billing: 'YES' | 'NO' | 'NO' | 'Se usa para facturar las ordenes a credito, si no tiene YES entonces no esta lista';
  note: string | null;
  paid_status: 'PENDING' | 'PAID' | 'PARTIALLY_PAID' | 'PENDING';
  paid_timetamp: string | Date | null;
  period_id: number | null;
  price_type_id: number;
  quote_id: number | null;
  sat_codigo_postal: string | null;
  sat_domicilio_fiscal_receptor: string;
  sat_exchange_rate: number;
  sat_factura_id: number | null;
  sat_forma_pago: string;
  sat_ieps: number;
  sat_isr: number;
  sat_pdf_attachment_id: number | null;
  sat_razon_social: string | null;
  sat_receptor_email: string | null;
  sat_receptor_rfc: string | null;
  sat_regimen_capital_receptor: string;
  sat_regimen_fiscal_receptor: string;
  sat_serie_consecutive: number | null;
  sat_serie: string | null;
  sat_uso_cfdi: string | null;
  sat_xml_attachment_id: number | null;
  service_type: 'TOGO' | 'IN_PLACE' | 'PICK_UP' | 'QUICK_SALE' | 'QUICK_SALE';
  shipping_address_id: number | null;
  shipping_cost: number;
  state: string | null;
  status: 'PENDING' | 'CANCELLED' | 'ACTIVE' | 'CLOSED' | 'PENDING_PAUSED' | 'PENDING' | 'Pendiente, la orden se esta tomando, se puede editar y cancelar sin ningun tipo de consideracion, no se a entregado al cliente, no tiene ningun tipo de pago, no se ha preparado\r\nActiva, La orden se esta ejecutando o se ejecuto, cuando ya tiene algun tipo de pago, se mando a credito o ya se entrego, Cancelada, la orden se cancelo, no se toma en cuenta.\r\nCLOSED. La venta ya se cerro, ya no se van agregar mas items, ya se envio pago y/o se metio a credito, De activa puede pasar a cancelada o cerrada pero no a pendiente ni pausada.\r\nDe pausada puede pasar a pendiente y viceversa.\r\nDe pausada puede pasar a cerrada';
  store_consecutive: number;
  store_id: number;
  subtotal: number;
  suburb: string | null;
  sync_id: string | null;
  system_activated: string | Date | null;
  table_id: number | null;
  tag: string | null;
  tax_percent: number;
  tax: number;
  total: number;
  updated: string | Date;
  version_created: string;
  version_updated: string;
}


