export interface Order_Item {
  id: number;
  commanda_id: number;
  commanda_status: string;
  created_by_user_id: number;
  created: string;
  delivered_qty: number;
  delivery_status: string;
  discount_percent: number;
  discount: number;
  exceptions: string;
  has_separator: string;
  ieps_calculated: number;
  ieps_type: string;
  ieps_value: number;
  id_payment: number;
  is_free_of_charge: string;
  is_item_extra: string;
  item_extra_id: number;
  item_group: number;
  item_id: number;
  item_option_id: number;
  item_option_qty: number;
  note: string;
  offer_id: number;
  order_id: number;
  original_unitary_price: number;
  paid_qty: number;
  preparation_status: string;
  price_id: number;
  qty: number;
  reservation_item_id: number;
  return_required: string;
  status: string;
  stock_status: string;
  subtotal: number;
  system_preparation_ended: string;
  system_preparation_started: string;
  tax_included: string;
  tax: number;
  total: number;
  type: string;
  unitary_price_meta: number;
  unitary_price: number;
  updated_by_user_id: number;
  updated: string;
}


