export interface Preferences {
  id: number;
  ask_for_guests_number: number;
  background_image_id: number | null;
  background_image_size: string | null;
  btn_primary_bg_color_hover: string | null;
  btn_primary_bg_color: string;
  btn_primary_border_color_hover: string;
  btn_primary_border_color: string | null;
  btn_primary_border_width: number;
  btn_primary_text_color_hover: string | null;
  btn_primary_text_color: string | null;
  btn_secondary_bg_color_hover: string | null;
  btn_secondary_bg_color: string | null;
  btn_secondary_border_color_hover: string | null;
  btn_secondary_border_color: string | null;
  btn_secondary_border_width: number;
  btn_secondary_text_color_hover: string | null;
  btn_secondary_text_color: string | null;
  button_border_radius: string;
  button_style: string | null;
  card_background_color: string | null;
  card_background_image_id: number | null;
  card_background_opacity: number;
  card_border_color: string | null;
  card_border_radius: string;
  charts_colors: string | null;
  chat_upload_attachment_image_id: number | null;
  chat_upload_image_id: number | null;
  comex_enabled: number;
  created: string | Date;
  currency_price_preference: string | null;
  default_cash_close_receipt: number;
  default_file_logo_image_id: number | null;
  default_input_type: string | null;
  default_pos_availability_type: string | null;
  default_price_type_id: number | null;
  default_print_receipt: number;
  default_product_image_id: number | null;
  default_return_action: string | null;
  default_ticket_format: number;
  default_ticket_image_id: number | null;
  default_user_logo_image_id: number | null;
  display_categories_on_items: string | null;
  ecommerce_enabled: number;
  header_background_color: string | null;
  header_text_color: string | null;
  item_selected_background_color: string;
  item_selected_text_color: string;
  link_color: string;
  link_hover: string;
  login_background_image_id: number | null;
  login_background_image_size: string | null;
  login_image_id: number | null;
  logo_image_id: number | null;
  menu_background_color: string;
  menu_background_image_id: number | null;
  menu_background_image_size: string | null;
  menu_background_type: string | null;
  menu_color_opacity: number;
  menu_icon_color: string;
  menu_text_color: string;
  menu_title_color: string;
  name: string;
  offers_enabled: number;
  pv_bar_background_color: string;
  pv_bar_text_color: string;
  pv_bar_total_color: string;
  pv_show_all_categories: string | null;
  pv_show_orders: string | null;
  radius_style: string | null;
  stock_negative_values_allowed: number;
  submenu_background_color: string;
  submenu_color_opacity: number;
  submenu_icon_color: string;
  submenu_text_color: string;
  text_color: string;
  titles_color: string | null;
  touch_size_button: string;
  touch_text_color: string;
  touch_text_shadow_color: string;
  update_prices_on_purchases: number;
  production_enabled: number;
  reservations_enabled: number;
  restaurant_enabled: number;
  updated: string;
  user_attachments: string | null;
  default_cash_close_type: string | null;
}


