export interface Store {
  id: number;
  accept_cash: any;
  accept_check: any;
  accept_credit_card: any;
  accept_delivery_orders: 'NEVER' | 'ONLY_PREPAID' | 'ALWAYS' | 'NEVER';
  accept_pickup_orders: 'NEVER' | 'ONLY_PREPAID' | 'ALWAYS' | 'NEVER';
  accept_transfer: any;
  address: string | null;
  autofacturacion_day_limit: number;
  autofacturacion_enabled: 'YES' | 'NO' | 'YES';
  autofacturacion_settings: 'ONLY_SAME_MONTH' | 'ONLY_DAY_LIMIT' | 'BOTH' | 'DISABLED' | 'ONLY_SAME_MONTH' | 'Si es ONLY_SAME_MONTH puede facturar siempre y cuando sea dentro del mismo mes de la facturacion.\r\nDAY_LIMIT solo si es antes de que pasen la cantidad de dias especificados despues de la compra.\r\n\r\nBOTH para facturar deben de cumplirse las dos condiciones debe ser dentro del mismo mes y ademas debe de ser dentro del limite de dias.';
  business_name: string | null;
  city: string | null;
  client_user_id: number | null;
  code: string | null;
  created_by_user_id: number | null;
  created: string | Date;
  default_billing_data_id: number | null;
  default_claveprodserv: string | null;
  default_currency_id: string;
  default_sat_item_name: string;
  default_sat_serie: string;
  electronic_transfer_percent_fee: number;
  exchange_rate: number;
  image_id: number | null;
  lat: number | null;
  lng: number | null;
  main_pc_ip: string | null;
  max_cash_amount: number;
  modo_facturacion: 'DESGLOSADA' | 'COMPACTA' | 'DESGLOSADA';
  name: string;
  offline_search_enabled: any;
  paypal_email: string | null;
  phone: string | null;
  pos_category_preferences: 'DEFAULT_BY_PRODUCT' | 'HIDE_BY_DEFAULT' | 'SHOW_BY_DEFAULT' | 'DEFAULT_BY_PRODUCT';
  price_list_id: number | null;
  print_receipt_copies: number;
  print_receipt: number | null;
  printer_ticket_config: string | null;
  production_enabled: any;
  qr_size: 'PERCENT_25' | 'PERCENT_50' | 'PERCENT_75' | 'PERCENT_100' | 'PERCENT_100';
  print_delay: number;
  print_mode: 'REDIRECT' | 'NEW_WINDOW' | 'POPUP' | 'NEW_WINDOW';
  rfc: string | null;
  sales_enabled: any;
  show_facturacion_qr: 'NO' | 'YES' | 'NO';
  state: string | null;
  status: 'ACTIVE' | 'DISABLED' | 'ACTIVE';
  suggested_tip: number;
  tax_percent: number;
  ticket_footer_text: string | null;
  ticket_image_id: number | null;
  updated_by_user_id: number | null;
  updated: string | Date;
  zipcode: string | null;
  ticket_address_display: 'SUCURSAL' | 'DIRECCION_FISCAL' | 'SUCURSAL' | 'Define qué dirección se muestra en el ticket: la de la sucursal o la fiscal';
}


