export interface Store {
  id: number;
  accept_cash: number;
  accept_check: number;
  accept_credit_card: number;
  accept_delivery_orders: string | null;
  accept_pickup_orders: string | null;
  accept_transfer: number;
  address: string | null;
  autofacturacion_day_limit: number;
  autofacturacion_enabled: string | null;
  autofacturacion_settings: string | null;
  business_name: string | null;
  city: string | null;
  client_user_id: number | null;
  code: string | null;
  created_by_user_id: number | null;
  created: string | Date;
  default_billing_data_id: number | null;
  default_claveprodserv: string | null;
  default_currency_id: string;
  default_sat_item_name: string;
  default_sat_serie: string;
  electronic_transfer_percent_fee: number | null;
  exchange_rate: number | null;
  image_id: number | null;
  lat: number | null;
  lng: number | null;
  main_pc_ip: string | null;
  max_cash_amount: number | null;
  modo_facturacion: string | null;
  name: string;
  offline_search_enabled: number;
  paypal_email: string | null;
  phone: string | null;
  pos_category_preferences: string | null;
  price_list_id: number | null;
  print_receipt_copies: number;
  print_receipt: number | null;
  printer_ticket_config: string | null;
  production_enabled: number;
  qr_size: string | null;
  print_delay: number;
  print_mode: string | null;
  rfc: string | null;
  sales_enabled: number;
  show_facturacion_qr: string | null;
  state: string | null;
  status: string | null;
  suggested_tip: number;
  tax_percent: number | null;
  ticket_footer_text: string | null;
  ticket_image_id: number | null;
  updated_by_user_id: number | null;
  updated: string;
  zipcode: string | null;
  ticket_address_display: string | null;
}


