export interface User_Permission {
  add_asistance: number;
  add_bills: number;
  add_commandas: number;
  add_credit_limit: number;
  add_credit_sales: number;
  add_form: number;
  add_items: number;
  add_item_points: number;
  add_marbetes: number;
  add_merma: number;
  add_offers: number;
  add_payments: number;
  add_payroll: number;
  add_providers: number;
  add_purchases: number;
  add_requisition: number;
  add_stock: number;
  add_user: number;
  advanced_order_search: number;
  approve_bill_payments: number;
  approve_requisition: number;
  asign_marbetes: number;
  caldos: number;
  cancel_closed_orders: number;
  cancel_ordered_item: number;
  cancel_payments: number;
  change_client_prices: number;
  created_by_user_id: number | null;
  created: string | Date;
  currency_rates: number;
  discounts: number;
  edit_billing_data: number;
  fullfill_orders: number;
  global_add_stock: number;
  global_bills: number;
  global_order_delivery: number;
  global_pos: number;
  global_prices: number;
  global_purchases: number;
  global_receive_shipping: number;
  reiniciar_facturacion: number;
  factura_global: number;
  facturar_orden: number;
  cancelar_factura: number;
  global_requisition: number;
  global_send_shipping: number;
  global_stats: number;
  hades: number;
  is_provider: number;
  open_cashier_box_anytime: number;
  order_delivery: number;
  pay_bills: number;
  pos: number;
  preferences: number;
  price_types: number;
  print_pre_receipt: number;
  production: number;
  purchases: number;
  pv_returns: number;
  quotes: number;
  receive_shipping: number;
  reports: number;
  return_money: number;
  add_roles: number;
  send_shipping: number;
  shipping_receive_type: string | null;
  show_tables: number;
  stocktake: number;
  store_prices: number;
  updated_by_user_id: number | null;
  updated: string;
  user_id: number;
  view_asistance: number;
  view_commandas: number;
  view_responses: number;
  view_stock_alerts: number;
  view_stock: number;
  view_reservations: number;
  delete_draft_items: number;
  add_accounts: number | null;
  view_accounts: number | null;
  pay_payrolls: number | null;
  view_payrolls: number | null;
  add_consumptions: number | null;
}


