export interface User_Permission {
  add_asistance: any;
  add_bills: any;
  add_commandas: any;
  add_credit_limit: any;
  add_credit_sales: any;
  add_form: any;
  add_items: any;
  add_item_points: any;
  add_marbetes: any;
  add_merma: any;
  add_offers: any;
  add_payments: any;
  add_payroll: any;
  add_providers: any;
  add_purchases: any;
  add_requisition: any;
  add_stock: any;
  add_user: any;
  advanced_order_search: any;
  approve_bill_payments: any;
  approve_requisition: any;
  asign_marbetes: any;
  caldos: any;
  cancel_closed_orders: any;
  cancel_ordered_item: any;
  cancel_payments: any;
  change_client_prices: any;
  created_by_user_id: number | null;
  created: string | Date;
  currency_rates: any;
  discounts: any;
  edit_billing_data: any;
  fullfill_orders: any;
  global_add_stock: any;
  global_bills: any;
  global_order_delivery: any;
  global_pos: any;
  global_prices: any;
  global_purchases: any;
  global_receive_shipping: any;
  reiniciar_facturacion: any;
  factura_global: any;
  facturar_orden: any;
  cancelar_factura: any;
  global_requisition: any;
  global_send_shipping: any;
  global_stats: any;
  hades: any;
  is_provider: any;
  open_cashier_box_anytime: any;
  order_delivery: any;
  pay_bills: any;
  pos: any;
  preferences: any;
  price_types: any;
  print_pre_receipt: any;
  production: any;
  purchases: any;
  pv_returns: any;
  quotes: any;
  receive_shipping: any;
  reports: any;
  return_money: any;
  add_roles: any;
  send_shipping: any;
  shipping_receive_type: 'VALIDATE' | 'CAPTURE_QTY' | 'CAPTURE_QTY';
  show_tables: any;
  stocktake: any;
  store_prices: any;
  updated_by_user_id: number | null;
  updated: string | Date;
  user_id: number;
  view_asistance: any;
  view_commandas: any;
  view_responses: any;
  view_stock_alerts: any;
  view_stock: any;
  view_reservations: any;
  delete_draft_items: any;
  add_accounts: any | null;
  view_accounts: any | null;
  pay_payrolls: any | null;
  view_payrolls: any | null;
  add_consumptions: any | null;
}


