import { Item } from '../RestModels/Item';

export function item(): Item {
	return {
		id: 0, 
		applicable_tax: 'DEFAULT', 
		availability_type: 'ON_STOCK', 
		background: '', 
		brand_id: null, 
		category_id: null, 
		clave_sat: null, 
		code: null, 
		commanda_type_id: null, 
		commission_currency_id: '', 
		commission_type: 'NONE', 
		commission: 0, 
		created_by_user_id: null, 
		created: new Date(), 
		currency_id: 'MXN', 
		description: null, 
		extra_name: null, 
		form_id: null, 
		response_requirement_qty: 'ONCE_PER_CLIENT', 
		for_reservation: 'YES', 
		has_serial_number: 'NO', 
		ieps_type: 'RATE', 
		ieps_value: 0, 
		image_id: null, 
		image_style: 'COVER', 
		json_tags: null, 
		measurement_unit: null, 
		name: '', 
		note_required: 'NO', 
		on_sale: 'NO', 
		stock_type: 'NORMAL', 
		partial_sale: 'NO', 
		period_type: 'BY_HOUR', 
		product_id: null, 
		provider_user_id: null, 
		reference_currency_id: '', 
		reference_price: 0, 
		return_action: 'RETURN_TO_STOCK', 
		shadow_color: '', 
		sort_weight: 0, 
		status: 'ACTIVE', 
		tax_percent: 0, 
		text_color: '', 
		text_style: 'NEVER', 
		unidad_medida_sat_id: '', 
		updated_by_user_id: null, 
		updated: new Date(), 
	};
}
