import { Offer } from '../RestModels/Offer';

export function offer(): Offer {
	return {
		id: 0, 
		category_id: null, 
		coupon_code: null, 
		created_by_user_id: 0, 
		created: new Date(), 
		description: null, 
		discount: 0, 
		gift_item_id: null, 
		hour_end: '', 
		hour_start: '', 
		image_id: null, 
		is_cumulative: 'NO', 
		is_valid_friday: '', 
		is_valid_monday: '', 
		is_valid_saturday: '', 
		is_valid_sunday: '', 
		is_valid_thursday: '', 
		is_valid_tuesday: '', 
		is_valid_wednesday: '', 
		item_id: null, 
		m: null, 
		n: null, 
		name: '', 
		status: 'ACTIVE', 
		store_id: null, 
		tag: null, 
		type: 'PERCENT_DISCOUNT', 
		updated_by_user_id: 0, 
		updated: new Date(), 
		valid_from: new Date(), 
		valid_thru: new Date(), 
		qty: 0, 
		price_type_id: null, 
		price: 0, 
	};
}
