import { Order_Item } from '../RestModels/Order_Item';

export function order_item(): Order_Item {
	return {
		id: 0, 
		commanda_id: null, 
		commanda_status: 'NOT_DISPLAYED', 
		created_by_user_id: null, 
		created: new Date(), 
		delivered_qty: 0, 
		delivery_status: 'PENDING', 
		discount_percent: 0, 
		discount: 0, 
		exceptions: null, 
		has_separator: 'NO', 
		ieps_calculated: 0, 
		ieps_type: 'RATE', 
		ieps_value: 0, 
		id_payment: null, 
		is_free_of_charge: 'NO', 
		is_item_extra: 'NO', 
		item_extra_id: null, 
		item_group: '', 
		item_id: 0, 
		item_option_id: null, 
		item_option_qty: 0, 
		note: null, 
		offer_id: null, 
		order_id: 0, 
		original_unitary_price: 0, 
		paid_qty: 0, 
		preparation_status: 'PENDING', 
		price_id: null, 
		qty: 0, 
		reservation_item_id: null, 
		return_required: 'NO', 
		status: 'ACTIVE', 
		stock_status: 'IN_STOCK', 
		subtotal: 0, 
		system_preparation_ended: null, 
		system_preparation_started: null, 
		tax_included: 'NO', 
		tax: 0, 
		total: 0, 
		type: 'NORMAL', 
		unitary_price_meta: 0, 
		unitary_price: 0, 
		updated_by_user_id: null, 
		updated: new Date(), 
	};
}
