import { Store } from '../RestModels/Store';

export function store(): Store {
	return {
		id: 0, 
		accept_cash: '', 
		accept_check: '', 
		accept_credit_card: '', 
		accept_delivery_orders: 'NEVER', 
		accept_pickup_orders: 'NEVER', 
		accept_transfer: '', 
		address: null, 
		autofacturacion_day_limit: 0, 
		autofacturacion_enabled: 'YES', 
		autofacturacion_settings: 'ONLY_SAME_MONTH', 
		business_name: null, 
		city: null, 
		client_user_id: null, 
		code: null, 
		created_by_user_id: null, 
		created: new Date(), 
		default_billing_data_id: null, 
		default_claveprodserv: null, 
		default_currency_id: '', 
		default_sat_item_name: '', 
		default_sat_serie: '', 
		electronic_transfer_percent_fee: 0, 
		exchange_rate: 0, 
		image_id: null, 
		lat: null, 
		lng: null, 
		main_pc_ip: null, 
		max_cash_amount: 0, 
		modo_facturacion: 'DESGLOSADA', 
		name: '', 
		offline_search_enabled: '', 
		paypal_email: null, 
		phone: null, 
		pos_category_preferences: 'DEFAULT_BY_PRODUCT', 
		price_list_id: null, 
		print_receipt_copies: 0, 
		print_receipt: null, 
		printer_ticket_config: null, 
		production_enabled: '', 
		qr_size: 'PERCENT_25', 
		print_delay: 0, 
		print_mode: 'REDIRECT', 
		rfc: null, 
		sales_enabled: '', 
		show_facturacion_qr: 'NO', 
		state: null, 
		status: 'ACTIVE', 
		suggested_tip: 0, 
		tax_percent: 0, 
		ticket_footer_text: null, 
		ticket_image_id: null, 
		updated_by_user_id: null, 
		updated: new Date(), 
		zipcode: null, 
		ticket_address_display: 'SUCURSAL', 
	};
}
