import * as empties from '../Empties';
import * as models from '../RestModels';

export class GetEmpty3 {
	static account(): models.Account { return empties.account(); }
	//static address(): models.Address { return empties.address(); }
	//static album(): models.Album { return empties.album(); }
	//static album_image(): models.Album_Image { return empties.album_image(); }
	//static answer(): models.Answer { return empties.answer(); }
	//static attachment(): models.Attachment { return empties.attachment(); }
	//static attribute(): models.Attribute { return empties.attribute(); }
	//static bank_account(): models.Bank_Account { return empties.bank_account(); }
	//static bank_movement(): models.Bank_Movement { return empties.bank_movement(); }
	//static bank_movement_bill(): models.Bank_Movement_Bill { return empties.bank_movement_bill(); }
	//static bank_movement_order(): models.Bank_Movement_Order { return empties.bank_movement_order(); }
	//static batch_record(): models.Batch_Record { return empties.batch_record(); }
	//static bill(): models.Bill { return empties.bill(); }
	//static billing_data(): models.Billing_Data { return empties.billing_data(); }
	//static box(): models.Box { return empties.box(); }
	//static box_content(): models.Box_Content { return empties.box_content(); }
	//static brand(): models.Brand { return empties.brand(); }
	//static cart_item(): models.Cart_Item { return empties.cart_item(); }
	//static cash_close(): models.Cash_Close { return empties.cash_close(); }
	//static cash_count(): models.Cash_Count { return empties.cash_count(); }
	//static cashier_withdrawal(): models.Cashier_Withdrawal { return empties.cashier_withdrawal(); }
	//static category(): models.Category { return empties.category(); }
	//static category_store(): models.Category_Store { return empties.category_store(); }
	//static category_tree(): models.Category_Tree { return empties.category_tree(); }
	//static category_type(): models.Category_Type { return empties.category_type(); }
	//static check_in(): models.Check_In { return empties.check_in(); }
	//static check_in_raw(): models.Check_In_Raw { return empties.check_in_raw(); }
	//static commanda(): models.Commanda { return empties.commanda(); }
	//static commanda_type(): models.Commanda_Type { return empties.commanda_type(); }
	//static consumption(): models.Consumption { return empties.consumption(); }
	//static consumption_user(): models.Consumption_User { return empties.consumption_user(); }
	//static currency(): models.Currency { return empties.currency(); }
	//static currency_rate(): models.Currency_Rate { return empties.currency_rate(); }
	//static delivery_assignment(): models.Delivery_Assignment { return empties.delivery_assignment(); }
	//static ecommerce(): models.Ecommerce { return empties.ecommerce(); }
	//static ecommerce_item(): models.Ecommerce_Item { return empties.ecommerce_item(); }
	//static ecommerce_item_profile(): models.Ecommerce_Item_Profile { return empties.ecommerce_item_profile(); }
	//static ecommerce_item_role(): models.Ecommerce_Item_Role { return empties.ecommerce_item_role(); }
	//static ecommerce_role_item(): models.Ecommerce_Role_Item { return empties.ecommerce_role_item(); }
	//static ecommerce_user(): models.Ecommerce_User { return empties.ecommerce_user(); }
	//static file_type(): models.File_Type { return empties.file_type(); }
	//static form(): models.Form { return empties.form(); }
	//static fund(): models.Fund { return empties.fund(); }
	//static image(): models.Image { return empties.image(); }
	//static ingredient(): models.Ingredient { return empties.ingredient(); }
	//static installment(): models.Installment { return empties.installment(); }
	//static item(): models.Item { return empties.item(); }
	//static item_attachment(): models.Item_Attachment { return empties.item_attachment(); }
	//static item_attribute(): models.Item_Attribute { return empties.item_attribute(); }
	//static item_exception(): models.Item_Exception { return empties.item_exception(); }
	//static item_image(): models.Item_Image { return empties.item_image(); }
	//static item_option(): models.Item_Option { return empties.item_option(); }
	//static item_option_value(): models.Item_Option_Value { return empties.item_option_value(); }
	//static item_points(): models.Item_Points { return empties.item_points(); }
	//static item_recipe(): models.Item_Recipe { return empties.item_recipe(); }
	//static item_store(): models.Item_Store { return empties.item_store(); }
	//static keyboard_shortcut(): models.Keyboard_Shortcut { return empties.keyboard_shortcut(); }
	//static labels(): models.Labels { return empties.labels(); }
	//static ledger(): models.Ledger { return empties.ledger(); }
	//static ledger_category(): models.Ledger_Category { return empties.ledger_category(); }
	//static ledger_detail(): models.Ledger_Detail { return empties.ledger_detail(); }
	//static merma(): models.Merma { return empties.merma(); }
	//static notification_token(): models.Notification_Token { return empties.notification_token(); }
	//static offer(): models.Offer { return empties.offer(); }
	//static order(): models.Order { return empties.order(); }
	//static order_item(): models.Order_Item { return empties.order_item(); }
	//static order_item_cost(): models.Order_Item_Cost { return empties.order_item_cost(); }
	//static order_item_exception(): models.Order_Item_Exception { return empties.order_item_exception(); }
	//static order_item_response(): models.Order_Item_Response { return empties.order_item_response(); }
	//static order_item_serial(): models.Order_Item_Serial { return empties.order_item_serial(); }
	//static order_offer(): models.Order_Offer { return empties.order_offer(); }
	//static pallet(): models.Pallet { return empties.pallet(); }
	//static pallet_content(): models.Pallet_Content { return empties.pallet_content(); }
	//static payment(): models.Payment { return empties.payment(); }
	//static paypal_access_token(): models.Paypal_Access_Token { return empties.paypal_access_token(); }
	//static paypal_order(): models.Paypal_Order { return empties.paypal_order(); }
	static payroll(): models.Payroll { return empties.payroll(); }
	//static payroll_concept(): models.Payroll_Concept { return empties.payroll_concept(); }
	//static payroll_value(): models.Payroll_Value { return empties.payroll_value(); }
	//static period(): models.Period { return empties.period(); }
	//static pharos_credentials(): models.Pharos_Credentials { return empties.pharos_credentials(); }
	//static pharos_payment_request(): models.Pharos_Payment_Request { return empties.pharos_payment_request(); }
	//static points_log(): models.Points_Log { return empties.points_log(); }
	//static post(): models.Post { return empties.post(); }
	//static preferences(): models.Preferences { return empties.preferences(); }
	//static price(): models.Price { return empties.price(); }
	//static price_list(): models.Price_List { return empties.price_list(); }
	//static price_log(): models.Price_Log { return empties.price_log(); }
	//static price_type(): models.Price_Type { return empties.price_type(); }
	//static printer(): models.Printer { return empties.printer(); }
	//static process(): models.Process { return empties.process(); }
	//static process_status(): models.Process_Status { return empties.process_status(); }
	//static product(): models.Product { return empties.product(); }
	//static production(): models.Production { return empties.production(); }
	//static production_area(): models.Production_Area { return empties.production_area(); }
	//static production_area_item(): models.Production_Area_Item { return empties.production_area_item(); }
	//static production_user(): models.Production_User { return empties.production_user(); }
	//static profile(): models.Profile { return empties.profile(); }
	//static purchase(): models.Purchase { return empties.purchase(); }
	//static purchase_detail(): models.Purchase_Detail { return empties.purchase_detail(); }
	//static push_notification(): models.Push_Notification { return empties.push_notification(); }
	//static question(): models.Question { return empties.question(); }
	//static question_choice(): models.Question_Choice { return empties.question_choice(); }
	//static quote(): models.Quote { return empties.quote(); }
	//static quote_item(): models.Quote_Item { return empties.quote_item(); }
	//static quote_request(): models.Quote_Request { return empties.quote_request(); }
	//static requisition(): models.Requisition { return empties.requisition(); }
	//static requisition_item(): models.Requisition_Item { return empties.requisition_item(); }
	//static reservation(): models.Reservation { return empties.reservation(); }
	//static reservation_item(): models.Reservation_Item { return empties.reservation_item(); }
	//static reservation_item_assign(): models.Reservation_Item_Assign { return empties.reservation_item_assign(); }
	//static reservation_item_serial(): models.Reservation_Item_Serial { return empties.reservation_item_serial(); }
	//static response(): models.Response { return empties.response(); }
	//static return_assignment(): models.Return_Assignment { return empties.return_assignment(); }
	//static returned_item(): models.Returned_Item { return empties.returned_item(); }
	//static returns(): models.Returns { return empties.returns(); }
	//static role(): models.Role { return empties.role(); }
	//static role_item_price(): models.Role_Item_Price { return empties.role_item_price(); }
	//static sat_factura(): models.Sat_Factura { return empties.sat_factura(); }
	//static sat_response(): models.Sat_Response { return empties.sat_response(); }
	//static serial(): models.Serial { return empties.serial(); }
	//static serial_image(): models.Serial_Image { return empties.serial_image(); }
	//static serial_log(): models.Serial_Log { return empties.serial_log(); }
	//static serie_counter(): models.Serie_Counter { return empties.serie_counter(); }
	//static session(): models.Session { return empties.session(); }
	//static shipping(): models.Shipping { return empties.shipping(); }
	//static shipping_item(): models.Shipping_Item { return empties.shipping_item(); }
	//static stock_alert(): models.Stock_Alert { return empties.stock_alert(); }
	//static stock_record(): models.Stock_Record { return empties.stock_record(); }
	//static stocktake(): models.Stocktake { return empties.stocktake(); }
	//static stocktake_item(): models.Stocktake_Item { return empties.stocktake_item(); }
	//static stocktake_scan(): models.Stocktake_Scan { return empties.stocktake_scan(); }
	//static storage(): models.Storage { return empties.storage(); }
	//static storage_item(): models.Storage_Item { return empties.storage_item(); }
	//static storage_serial(): models.Storage_Serial { return empties.storage_serial(); }
	//static storage_type(): models.Storage_Type { return empties.storage_type(); }
	static store(): models.Store { return empties.store(); }
	//static store_bank_account(): models.Store_Bank_Account { return empties.store_bank_account(); }
	//static store_sale_report(): models.Store_Sale_Report { return empties.store_sale_report(); }
	//static table(): models.Table { return empties.table(); }
	//static task(): models.Task { return empties.task(); }
	//static task_comment(): models.Task_Comment { return empties.task_comment(); }
	//static ticket(): models.Ticket { return empties.ticket(); }
	//static unidad_medida_sat(): models.Unidad_Medida_Sat { return empties.unidad_medida_sat(); }
	static user(): models.User { return empties.user(); }
	//static user_attachment(): models.User_Attachment { return empties.user_attachment(); }
	//static user_extra_fields(): models.User_Extra_Fields { return empties.user_extra_fields(); }
	static user_permission(): models.User_Permission { return empties.user_permission(); }
	//static withdrawal(): models.Withdrawal { return empties.withdrawal(); }
	//static work_log(): models.Work_Log { return empties.work_log(); }
	//static work_log_rules(): models.Work_Log_Rules { return empties.work_log_rules(); }
	//static workshift(): models.Workshift { return empties.workshift(); }
}
